const devilFruits = {

  // ─────────────────────────────────────────────
  // LOGIA
  // ─────────────────────────────────────────────
  logia: [
    {
      id: "moku-moku",
      name: "Moku Moku no Mi",
      englishName: "Smoke-Smoke Fruit",
      ability: "Grants the ability to create, control, and transform into smoke. The user can engulf and restrain opponents inside dense smoke clouds.",
      chapter: 100,
      arc: "Loguetown Arc",
      previousOwners: [],
      currentOwner: "Smoker",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "mera-mera",
      name: "Mera Mera no Mi",
      englishName: "Flame-Flame Fruit",
      ability: "Allows the user to create, control, and transform into fire at will.",
      chapter: 154,
      arc: "Alabasta Arc",
      previousOwners: ["Portgas D. Ace"],
      currentOwner: "Sabo",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "suna-suna",
      name: "Suna Suna no Mi",
      englishName: "Sand-Sand Fruit",
      ability: "Lets the user create, control, and transform into sand. Can absorb moisture from anything on contact, desiccating opponents instantly.",
      chapter: 170,
      arc: "Alabasta Arc",
      previousOwners: [],
      currentOwner: "Crocodile",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "goro-goro",
      name: "Goro Goro no Mi",
      englishName: "Rumble-Rumble Fruit",
      ability: "Allows the user to create, control, and transform into lightning. Enel considered it invincible — only rubber negates it.",
      chapter: 254,
      arc: "Skypiea Arc",
      previousOwners: [],
      currentOwner: "Enel",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "hie-hie",
      name: "Hie Hie no Mi",
      englishName: "Ice-Ice Fruit",
      ability: "Allows the user to create, control, and transform into ice. Can freeze anything it contacts and cool large bodies of water.",
      chapter: 319,
      arc: "Long Ring Long Land Arc",
      previousOwners: [],
      currentOwner: "Kuzan (Aokiji)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "yami-yami",
      name: "Yami Yami no Mi",
      englishName: "Dark-Dark Fruit",
      ability: "Grants control over darkness and gravity. Uniquely, it cannot nullify damage and can absorb and nullify other Devil Fruit powers on contact.",
      chapter: 440,
      arc: "Post-Enies Lobby Arc",
      previousOwners: [],
      currentOwner: "Marshall D. Teach (Blackbeard)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "pika-pika",
      name: "Pika Pika no Mi",
      englishName: "Glint-Glint Fruit",
      ability: "Grants the power to create, control, and transform into light — allowing attacks and movement at the speed of light.",
      chapter: 504,
      arc: "Sabaody Archipelago Arc",
      previousOwners: [],
      currentOwner: "Borsalino (Kizaru)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "magu-magu",
      name: "Magu Magu no Mi",
      englishName: "Magma-Magma Fruit",
      ability: "Grants the ability to create, control, and transform into magma. Considered the highest offensive Logia — magma burns even fire.",
      chapter: 557,
      arc: "Marineford Arc",
      previousOwners: [],
      currentOwner: "Sakazuki (Akainu)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "numa-numa",
      name: "Numa Numa no Mi",
      englishName: "Swamp-Swamp Fruit",
      ability: "Turns the user into a living swamp, capable of absorbing anything into their body regardless of size and storing it indefinitely.",
      chapter: 600,
      arc: "Return to Sabaody Arc",
      previousOwners: [],
      currentOwner: "Caribou",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "gasu-gasu",
      name: "Gasu Gasu no Mi",
      englishName: "Gas-Gas Fruit",
      ability: "Grants the ability to create, control, and transform into gas. The user can produce lethal poison gas, explosions, and manipulate oxygen levels.",
      chapter: 658,
      arc: "Punk Hazard Arc",
      previousOwners: [],
      currentOwner: "Caesar Clown",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "yuki-yuki",
      name: "Yuki Yuki no Mi",
      englishName: "Snow-Snow Fruit",
      ability: "Allows the user to create, control, and transform into snow. Unlike ice, snow is freely shapeable and can be used to camouflage or smother opponents.",
      chapter: 681,
      arc: "Punk Hazard Arc",
      previousOwners: [],
      currentOwner: "Monet (deceased — fruit reincarnated)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "mori-mori",
      name: "Mori Mori no Mi",
      englishName: "Woods-Woods Fruit",
      ability: "Allows the user to create, control, and transform into plant life — growing enormous trees, vines, and roots from any surface.",
      chapter: 1054,
      arc: "Wano Country Post-Arc",
      previousOwners: [],
      currentOwner: "Aramaki (Ryokugyu)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "susu-susu",
      name: "Susu Susu no Mi",
      englishName: "Soot-Soot Fruit",
      ability: "Allows the user to create, control, and transform into soot and smoke particulates. Used to form ravens and spread darkness across an area.",
      chapter: 904,
      arc: "Levely Arc",
      previousOwners: [],
      currentOwner: "Karasu",
      awakened: false,
      awakeningAbility: null,
      recent: false
    }
  ],

  // ─────────────────────────────────────────────
  // ZOAN
  // ─────────────────────────────────────────────
  zoan: [
    // ── REGULAR ──
    {
      id: "hito-hito",
      name: "Hito Hito no Mi",
      englishName: "Human-Human Fruit",
      subtype: "Regular",
      ability: "Allows a non-human to transform into a human or human hybrid, granting human-level intelligence. Chopper uses medical knowledge to unlock multiple transformations via Rumble Balls.",
      chapter: 140,
      arc: "Drum Island Arc",
      previousOwners: [],
      currentOwner: "Tony Tony Chopper",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "inu-inu-dachshund",
      name: "Inu Inu no Mi, Model: Dachshund",
      englishName: "Dog-Dog Fruit, Dachshund Model",
      subtype: "Regular",
      ability: "Transforms the user into a dachshund or dachshund-human hybrid. Eaten by Lassoo — Mr. 4's gun dog companion — granting the gun itself animal sentience and transformation.",
      chapter: 168,
      arc: "Alabasta Arc",
      previousOwners: [],
      currentOwner: "Lassoo (Mr. 4's dog gun)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "ushi-ushi-bison",
      name: "Ushi Ushi no Mi, Model: Bison",
      englishName: "Ox-Ox Fruit, Bison Model",
      subtype: "Regular",
      ability: "Allows transformation into a bison or bison-human hybrid with tremendous charging and trampling power.",
      chapter: 139,
      arc: "Drum Island Arc",
      previousOwners: [],
      currentOwner: "Dalton",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "mogu-mogu",
      name: "Mogu Mogu no Mi",
      englishName: "Mole-Mole Fruit",
      subtype: "Regular",
      ability: "Allows transformation into a giant mole or mole-human hybrid, enabling high-speed underground tunneling and ambush attacks.",
      chapter: 168,
      arc: "Alabasta Arc",
      previousOwners: [],
      currentOwner: "Miss Merry Christmas",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "inu-inu-jackal",
      name: "Inu Inu no Mi, Model: Jackal",
      englishName: "Dog-Dog Fruit, Jackal Model",
      subtype: "Regular",
      ability: "Allows transformation into a full jackal or jackal-human hybrid with enhanced speed and combat instincts.",
      chapter: 153,
      arc: "Alabasta Arc",
      previousOwners: [],
      currentOwner: "Chaka",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "tori-tori-falcon",
      name: "Tori Tori no Mi, Model: Falcon",
      englishName: "Bird-Bird Fruit, Falcon Model",
      subtype: "Regular",
      ability: "Grants the ability to transform into a falcon or falcon-human hybrid with flight and powerful talons.",
      chapter: 153,
      arc: "Alabasta Arc",
      previousOwners: [],
      currentOwner: "Pell",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "uma-uma-horse",
      name: "Uma Uma no Mi",
      englishName: "Horse-Horse Fruit",
      subtype: "Regular",
      ability: "Transforms the user into a horse or horse-human hybrid. Pierre, Gan Fall's steed, uses this fruit — granting the animal full sentience.",
      chapter: 254,
      arc: "Skypiea Arc",
      previousOwners: [],
      currentOwner: "Pierre (Gan Fall's horse)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "neko-neko-leopard",
      name: "Neko Neko no Mi, Model: Leopard",
      englishName: "Cat-Cat Fruit, Leopard Model",
      subtype: "Regular",
      ability: "Transforms the user into a full leopard or leopard-human hybrid with immense speed and strength.",
      chapter: 425,
      arc: "Enies Lobby Arc",
      previousOwners: [],
      currentOwner: "Rob Lucci",
      awakened: true,
      awakeningAbility: "Awakened during the Egghead Arc — grants a dramatically enlarged and more powerful hybrid form with greatly amplified destructive force.",
      recent: false
    },
    {
      id: "inu-inu-wolf",
      name: "Inu Inu no Mi, Model: Wolf",
      englishName: "Dog-Dog Fruit, Wolf Model",
      subtype: "Regular",
      ability: "Transforms the user into a wolf or wolf-human hybrid with powerful jaws and ferocious combat instincts.",
      chapter: 425,
      arc: "Enies Lobby Arc",
      previousOwners: [],
      currentOwner: "Jabra",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "zou-zou-elephant",
      name: "Zou Zou no Mi",
      englishName: "Elephant-Elephant Fruit",
      subtype: "Regular",
      ability: "Transforms the user into an elephant or elephant-human hybrid. Funkfreed is a sword that ate the fruit, becoming a sentient elephant-sword hybrid.",
      chapter: 391,
      arc: "Enies Lobby Arc",
      previousOwners: [],
      currentOwner: "Funkfreed (Spandam's sword)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "ushi-ushi-giraffe",
      name: "Ushi Ushi no Mi, Model: Giraffe",
      englishName: "Ox-Ox Fruit, Giraffe Model",
      subtype: "Regular",
      ability: "Allows the user to transform into a giraffe or giraffe-human hybrid, granting immense neck and leg striking power.",
      chapter: 402,
      arc: "Water 7 Arc",
      previousOwners: [],
      currentOwner: "Kaku",
      awakened: true,
      awakeningAbility: "Awakened during the Egghead Arc — produces a giraffe-armored exo-form with vastly amplified power and a more controlled transformation.",
      recent: false
    },
    {
      id: "hebi-hebi-anaconda",
      name: "Hebi Hebi no Mi, Model: Anaconda",
      englishName: "Snake-Snake Fruit, Anaconda Model",
      subtype: "Regular",
      ability: "Allows transformation into an anaconda or anaconda-human hybrid with powerful constriction and large size.",
      chapter: 521,
      arc: "Amazon Lily Arc",
      previousOwners: [],
      currentOwner: "Boa Sandersonia",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "hebi-hebi-cobra",
      name: "Hebi Hebi no Mi, Model: King Cobra",
      englishName: "Snake-Snake Fruit, King Cobra Model",
      subtype: "Regular",
      ability: "Allows transformation into a king cobra or cobra-human hybrid with venomous bite attacks and massive scale.",
      chapter: 521,
      arc: "Amazon Lily Arc",
      previousOwners: [],
      currentOwner: "Boa Marigold",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "sara-sara-axolotl",
      name: "Sara Sara no Mi, Model: Axolotl",
      englishName: "Sala-Sala Fruit, Axolotl Model",
      subtype: "Regular",
      ability: "Transforms the user into an axolotl or axolotl-human hybrid. Smiley, a giant slime weapon, ate this fruit and gained sapience and transformation ability.",
      chapter: 655,
      arc: "Punk Hazard Arc",
      previousOwners: [],
      currentOwner: "Smiley (deceased)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "mushi-mushi-beetle",
      name: "Mushi Mushi no Mi, Model: Rhinoceros Beetle",
      englishName: "Bug-Bug Fruit, Rhinoceros Beetle Model",
      subtype: "Regular",
      ability: "Transforms the user into a rhinoceros beetle or beetle-human hybrid, granting flight and powerful horn attacks.",
      chapter: 720,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Kabu",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "mushi-mushi-hornet",
      name: "Mushi Mushi no Mi, Model: Hornet",
      englishName: "Bug-Bug Fruit, Hornet Model",
      subtype: "Regular",
      ability: "Transforms the user into a hornet or hornet-human hybrid, granting flight and venomous stinger attacks.",
      chapter: 720,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Bian",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "kame-kame",
      name: "Kame Kame no Mi",
      englishName: "Turtle-Turtle Fruit",
      subtype: "Regular",
      ability: "Transforms the user into a turtle or turtle-human hybrid with an extremely durable shell used as impenetrable defense.",
      chapter: 827,
      arc: "Whole Cake Island Arc",
      previousOwners: [],
      currentOwner: "Pekoms",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    // ── ANCIENT ZOAN ──
    {
      id: "zou-zou-mammoth",
      name: "Zou Zou no Mi, Model: Mammoth",
      englishName: "Elephant-Elephant Fruit, Mammoth Model",
      subtype: "Ancient",
      ability: "Transforms the user into a colossal mammoth — one of the largest Ancient Zoan forms — with overwhelming physical mass and power.",
      chapter: 793,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Jack",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "ryu-ryu-allosaurus",
      name: "Ryu Ryu no Mi, Model: Allosaurus",
      englishName: "Dragon-Dragon Fruit, Allosaurus Model",
      subtype: "Ancient",
      ability: "Transforms the user into an allosaurus — a massive predatory dinosaur — with devastating jaw strength and speed.",
      chapter: 938,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "X Drake",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "ryu-ryu-spinosaurus",
      name: "Ryu Ryu no Mi, Model: Spinosaurus",
      englishName: "Dragon-Dragon Fruit, Spinosaurus Model",
      subtype: "Ancient",
      ability: "Grants transformation into a spinosaurus — one of the largest predatory dinosaurs — with enormous biting power and tail strikes.",
      chapter: 929,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Page One",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "ryu-ryu-pteranodon",
      name: "Ryu Ryu no Mi, Model: Pteranodon",
      englishName: "Dragon-Dragon Fruit, Pteranodon Model",
      subtype: "Ancient",
      ability: "Allows transformation into a pteranodon, granting flight, high-speed aerial combat, and devastating beak strikes.",
      chapter: 996,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "King (Alber)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "ryu-ryu-brachiosaurus",
      name: "Ryu Ryu no Mi, Model: Brachiosaurus",
      englishName: "Dragon-Dragon Fruit, Brachiosaurus Model",
      subtype: "Ancient",
      ability: "Transforms the user into a massive brachiosaurus with extreme reach, crushing force, and a towering neck used as a weapon.",
      chapter: 984,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Queen",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "ryu-ryu-triceratops",
      name: "Ryu Ryu no Mi, Model: Triceratops",
      englishName: "Dragon-Dragon Fruit, Triceratops Model",
      subtype: "Ancient",
      ability: "Grants the ability to transform into a triceratops with armored horns, a powerful neck frill shield, and devastating charges.",
      chapter: 985,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Sasaki",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "ryu-ryu-pachycephalosaurus",
      name: "Ryu Ryu no Mi, Model: Pachycephalosaurus",
      englishName: "Dragon-Dragon Fruit, Pachycephalosaurus Model",
      subtype: "Ancient",
      ability: "Allows transformation into a pachycephalosaurus — a thick-skulled dinosaur — with devastating headbutt attacks.",
      chapter: 978,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Ulti",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "kumo-kumo-rosamygale",
      name: "Kumo Kumo no Mi, Model: Rosamygale Grauvogeli",
      englishName: "Spider-Spider Fruit, Rosamygale Grauvogeli Model",
      subtype: "Ancient",
      ability: "Transforms the user into a Rosamygale Grauvogeli — a prehistoric spider — with multiple limbs, webbing, and a massive hybrid body.",
      chapter: 1005,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Black Maria",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "neko-neko-saber-tiger",
      name: "Neko Neko no Mi, Model: Saber Tiger",
      englishName: "Cat-Cat Fruit, Saber Tiger Model",
      subtype: "Ancient",
      ability: "Transforms the user into a saber-toothed tiger — a prehistoric apex predator — with massive fangs and ferocious power.",
      chapter: 1019,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Who's-Who",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "ryu-ryu-nidhogg",
      name: "Ryu Ryu no Mi, Model: Nidhogg",
      englishName: "Dragon-Dragon Fruit, Nidhogg Model",
      subtype: "Ancient",
      ability: "Transforms the user into the Níðhöggr — the mythological dragon of Norse legend that gnaws at the roots of Yggdrasil — with immense draconic power.",
      chapter: 1119,
      arc: "Elbaph Arc",
      previousOwners: [],
      currentOwner: "Loki",
      awakened: false,
      awakeningAbility: null,
      recent: true
    },
    // ── MYTHICAL ZOAN ──
    {
      id: "tori-tori-phoenix",
      name: "Tori Tori no Mi, Model: Phoenix",
      englishName: "Bird-Bird Fruit, Phoenix Model",
      subtype: "Mythical",
      ability: "Transforms the user into a phoenix or phoenix-human hybrid. The blue regenerative flames heal the user and anyone they touch.",
      chapter: 553,
      arc: "Marineford Arc",
      previousOwners: [],
      currentOwner: "Marco",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "hito-hito-daibutsu",
      name: "Hito Hito no Mi, Model: Daibutsu",
      englishName: "Human-Human Fruit, Giant Buddha Model",
      subtype: "Mythical",
      ability: "Transforms the user into a massive golden Buddha capable of emitting powerful shockwaves across a wide area.",
      chapter: 577,
      arc: "Marineford Arc",
      previousOwners: [],
      currentOwner: "Sengoku",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "uo-uo-seiryu",
      name: "Uo Uo no Mi, Model: Seiryu",
      englishName: "Fish-Fish Fruit, Azure Dragon Model",
      subtype: "Mythical",
      ability: "Transforms the user into an Azure Dragon — the strongest creature in the world. Grants fire breath, Flame Clouds, and weather control.",
      chapter: 921,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Kaidou",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "hebi-hebi-yamata",
      name: "Hebi Hebi no Mi, Model: Yamata no Orochi",
      englishName: "Snake-Snake Fruit, Eight-Headed Serpent Model",
      subtype: "Mythical",
      ability: "Transforms the user into the eight-headed Yamata no Orochi of Japanese myth. Each head can act independently and regenerates when severed.",
      chapter: 926,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Kurozumi Orochi (deceased — fruit reincarnated)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "inu-inu-okuchi",
      name: "Inu Inu no Mi, Model: Okuchi no Makami",
      englishName: "Dog-Dog Fruit, Divine Wolf Model",
      subtype: "Mythical",
      ability: "Transforms the user into a massive divine wolf from Japanese mythology. Grants ice breath and immense physical power.",
      chapter: 1020,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Yamato",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "inu-inu-kyubi",
      name: "Inu Inu no Mi, Model: Kyubi no Kitsune",
      englishName: "Dog-Dog Fruit, Nine-Tailed Fox Model",
      subtype: "Mythical",
      ability: "Transforms the user into a nine-tailed fox of Japanese legend. Grants the ability to perfectly replicate anyone's appearance — a perfect disguise.",
      chapter: 925,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Catarina Devon",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "hito-hito-onyudo",
      name: "Hito Hito no Mi, Model: Onyudo",
      englishName: "Human-Human Fruit, Monk Model",
      subtype: "Mythical",
      ability: "Transforms the user into a giant monk spirit from Japanese folklore. Grants enormous size and the ability to shrink objects upon touch.",
      chapter: 953,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Onimaru (Gyukimaru)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "inu-inu-tanuki",
      name: "Inu Inu no Mi, Model: Tanuki",
      englishName: "Dog-Dog Fruit, Tanuki Model",
      subtype: "Mythical",
      ability: "Transforms the user into a tanuki — a mythological raccoon dog known for shapeshifting in Japanese folklore.",
      chapter: 947,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Bunbuku",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "uma-uma-pegasus",
      name: "Uma Uma no Mi, Model: Pegasus",
      englishName: "Horse-Horse Fruit, Pegasus Model",
      subtype: "Mythical",
      ability: "Transforms the user into a winged horse of Greek myth, granting flight and the ability to produce clouds from its body.",
      chapter: 785,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Stronger (Doc Q's horse)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "hito-hito-nika",
      name: "Hito Hito no Mi, Model: Nika",
      englishName: "Human-Human Fruit, Sun God Nika Model",
      subtype: "Mythical",
      ability: "The most ridiculous power in existence. The user's body gains limitless rubber properties with no structural constraints. In awakening, the user can affect the environment with rubbery properties and fight with the freedom of the legendary warrior Nika.",
      chapter: 1,
      arc: "Romance Dawn Arc (true identity revealed Ch. 1044, Wano Country Arc)",
      previousOwners: ["Unknown ancient owner (fruit stolen and hidden by World Government, labeled 'Gomu Gomu no Mi')"],
      currentOwner: "Monkey D. Luffy",
      awakened: true,
      awakeningAbility: "Gear 5 — the user's body and surroundings take on rubbery properties. The user can reshape terrain, create giant limbs from the environment, and fight with limitless cartoon-like freedom.",
      recent: false
    },

    // ── ARTIFICIAL ──
    {
      id: "art-uo-uo-seiryu",
      name: "Artificial Uo Uo no Mi, Model: Seiryu",
      englishName: "Artificial Fish-Fish Fruit, Azure Dragon Model",
      subtype: "Mythical",
      artificial: true,
      ability: "A man-made replica of Kaidou's Mythical Zoan created by Dr. Vegapunk. Grants Momonosuke the ability to transform into a pink Azure Dragon — though its powers differ slightly from the original.",
      chapter: 685,
      arc: "Punk Hazard Arc",
      previousOwners: [],
      currentOwner: "Kozuki Momonosuke",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-hitsuji",
      name: "Hitsuji no SMILE",
      englishName: "Sheep SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a sheep. Sheepshead can turn his hands into curled ram horns for charging attacks. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 795,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Sheepshead and unnamed Gifters",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-risu",
      name: "Risu no SMILE",
      englishName: "Squirrel SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a squirrel. Ginrummy's cheeks can puff out like a squirrel's when she eats. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 795,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Ginrummy",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-nezumi",
      name: "Nezumi no SMILE",
      englishName: "Mouse SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a mouse, giving the user large mouse ears. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 808,
      arc: "Zou Arc",
      previousOwners: [],
      currentOwner: "Mouseman and unnamed Gifters",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-kani",
      name: "Kani no SMILE",
      englishName: "Crab SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a crab — crab claws in place of hands, and in some users extra legs and eyestalks. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 808,
      arc: "Zou Arc",
      previousOwners: [],
      currentOwner: "Nightcrab Girl and unnamed Gifters",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-okami",
      name: "Okami no SMILE",
      englishName: "Wolf SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a wolf. Redwolf has a wolf's head and torso growing from his abdomen; others can turn a hand into a wolf's head. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 809,
      arc: "Zou Arc",
      previousOwners: [],
      currentOwner: "Redwolf and unnamed Gifters",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-nokogirikuwagata",
      name: "Nokogirikuwagata no SMILE",
      englishName: "Japanese Stag Beetle SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a stag beetle — serrated beetle jaws and, for Nokokuwa Police, an extra pair of arms. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 810,
      arc: "Zou Arc",
      previousOwners: [],
      currentOwner: "Nokokuwa Police and unnamed Gifters",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-gorira",
      name: "Gorira no SMILE",
      englishName: "Gorilla SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a gorilla. Briscola's left arm becomes a gorilla's upper body; Mizerka has gorillas growing from her arms and hips. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 810,
      arc: "Zou Arc",
      previousOwners: [],
      currentOwner: "Briscola, Mizerka, and unnamed Gifters",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-komori",
      name: "Komori no SMILE",
      englishName: "Bat SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a bat — bat ears, fangs, and in Batman's case bat wings on his lower body. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 914,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Batman and unnamed Gifters",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-gazeru",
      name: "Gazeru no SMILE",
      englishName: "Gazelle SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a gazelle. Gazelleman gains powerful gazelle legs and horns for high-speed kicks. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 914,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Gazelleman",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-raion",
      name: "Raion no SMILE",
      englishName: "Lion SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a lion. Holed'em has a fire-breathing lion's head and forelegs growing from his waist. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 915,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Holed'em and unnamed Gifters",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-uma",
      name: "Uma no SMILE",
      englishName: "Horse SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a horse. Speed's lower body becomes a horse, while Orochi's carriage bearers gain horse legs. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 917,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Speed, Fuga, Hoisassa, Horseman, and unnamed Gifters",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-hebi",
      name: "Hebi no SMILE",
      englishName: "Snake SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a snake. Snakeman has a snake passing through his body; Sarahebi can stretch her neck and grow fangs. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 918,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Snakeman, Sarahebi, and unnamed Gifters",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-kaba",
      name: "Kaba no SMILE",
      englishName: "Hippopotamus SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a hippopotamus. Dobon has a hippo snout and a hippo's body growing from the backs of his legs. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 926,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Dobon",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-arupaka",
      name: "Arupaka no SMILE",
      englishName: "Alpaca SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of an alpaca, giving Alpacaman an alpaca's head and long neck. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 934,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Alpacaman",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-sasori",
      name: "Sasori no SMILE",
      englishName: "Scorpion SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a scorpion — extra scorpion legs, pincers, and a venomous stinger. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 934,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Daifugo, Scorpionlady",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-zo",
      name: "Zo no SMILE",
      englishName: "Elephant SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of an elephant. Babanuki has an elephant's head growing from his chest and fires water from its trunk. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 934,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Babanuki and unnamed Gifters",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-saru",
      name: "Saru no SMILE",
      englishName: "Monkey SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a monkey. Solitaire gains a monkey tail and an extra pair of monkey limbs. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 935,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Solitaire and unnamed Gifters",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-arumajiro",
      name: "Arumajiro no SMILE",
      englishName: "Armadillo SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of an armadillo. Madilloman carries an armadillo with a giant armored shell on his back. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 939,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Madilloman",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-dacho",
      name: "Dacho no SMILE",
      englishName: "Ostrich SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of an ostrich, giving Dachoman a long, feathered ostrich neck. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 940,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Dachoman",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-taka",
      name: "Taka no SMILE",
      englishName: "Hawk SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a hawk — a hawk's head on the scalp, feathers, and wings capable of flight. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 959,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Hawkman",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-agehacho",
      name: "Agehacho no SMILE",
      englishName: "Swallowtail Butterfly SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a swallowtail butterfly — butterfly wings and antennae that allow flight. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 959,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Ageha Woman",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-hayabusa",
      name: "Hayabusa no SMILE",
      englishName: "Peregrine Falcon SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a peregrine falcon, giving Koshi Falcon large falcon wings for flight. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 959,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Koshi Falcon",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-zogame",
      name: "Zogame no SMILE",
      englishName: "Giant Tortoise SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a giant tortoise. The user's legs are replaced by a whole tortoise body growing from the pelvis. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 978,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Usunoro and unnamed Gifters",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-kirin",
      name: "Kirin no SMILE",
      englishName: "Giraffe SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a giraffe. Hamlet has a giraffe's neck and body growing from his upper back. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 978,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Hamlet and unnamed Gifters",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-musasabi",
      name: "Musasabi no SMILE",
      englishName: "Flying Squirrel SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a flying squirrel, giving Bao Huang a bushy tail and the ability to glide through the air. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 979,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Bao Huang",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-suzumebachi",
      name: "Suzumebachi no SMILE",
      englishName: "Wasp SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a hornet, giving Beegirl wings and an extra pair of arms. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 980,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Beegirl",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-shoryobatta",
      name: "Shoryobatta no SMILE",
      englishName: "Chinese Grasshopper SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a Chinese grasshopper, giving Jumper grasshopper wings and mandibles. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 980,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Jumper",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-kurumabatta",
      name: "Kurumabatta no SMILE",
      englishName: "Gastrimargus Grasshopper SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a Gastrimargus grasshopper, sharpening Battaman's fingers into claws. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 980,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Battaman",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-nanafushi",
      name: "Nanafushi no SMILE",
      englishName: "Phasmid SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a stick insect, giving Chochinman long, thin arms. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 980,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Chochinman",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-fukuro",
      name: "Fukuro no SMILE",
      englishName: "Owl SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of an owl. Both Doubt Brothers ate one. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 980,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Doubt Brothers",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-shirohebi",
      name: "Shirohebi no SMILE",
      englishName: "White Snake SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a white snake, turning Tenjo-Sagari's lower body into a long snake tail. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 980,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Tenjo-Sagari",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-kabutomushi",
      name: "Kabutomushi no SMILE",
      englishName: "Japanese Rhinoceros Beetle SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a rhinoceros beetle — a large horn on the forehead and an extra pair of arms. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 983,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Beetleman",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-kamakiri",
      name: "Kamakiri no SMILE",
      englishName: "Praying Mantis SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a praying mantis, such as scythe-like mantis claws in place of hands. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 983,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Kamakirigirl and unnamed Gifters",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-sai",
      name: "Sai no SMILE",
      englishName: "Rhinoceros SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a rhinoceros. Saitank's legs are replaced by a whole rhino, with his torso emerging from its back. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 993,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Saitank and unnamed Gifters",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-harinezumi",
      name: "Harinezumi no SMILE",
      englishName: "Hedgehog SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a hedgehog, turning all of Bisley's hair into sharp spines. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 993,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Bisley",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-kokasasuokabuto",
      name: "Kokasasuokabuto no SMILE",
      englishName: "Caucasus Beetle SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a Caucasus beetle — three horns on the head and an extra pair of arms. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 993,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Caucasusman",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-niwatori",
      name: "Niwatori no SMILE",
      englishName: "Chicken SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a chicken. Fourtricks has a chicken growing out of his back. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 994,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Fourtricks and unnamed Gifters",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-garagarahebi",
      name: "Garagarahebi no SMILE",
      englishName: "Rattlesnake SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a rattlesnake. Poker's legs become a rattlesnake's head and tail, its body looping through his shoulders. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 997,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Poker",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-nishikihebi",
      name: "Nishikihebi no SMILE",
      englishName: "Python SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a python. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 998,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Bishonure-Onna",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-aodaisho",
      name: "Aodaisho no SMILE",
      englishName: "Japanese Rat Snake SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a Japanese rat snake. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 998,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Yamanba",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-shishibanahebi",
      name: "Shishibanahebi no SMILE",
      englishName: "Hognose Snake SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a hognose snake, making Nure-Onna's neck long and snake-like. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 998,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Nure-Onna",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-kaiman",
      name: "Kaiman no SMILE",
      englishName: "Caiman SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a caiman. Caimanlady has the front half of a caiman growing from the backs of her lower legs. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 1004,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Caimanlady",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "smile-pagu",
      name: "Pagu no SMILE",
      englishName: "Pug SMILE",
      subtype: "Regular",
      artificial: true,
      ability: "Grants traits of a pug, turning Wanyudo's whole body except his head into a pug's. Like all SMILEs, it was mass-produced by Caesar Clown from SAD — a failed SMILE instead leaves the eater unable to stop smiling.",
      chapter: 1005,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Wanyudo",
      awakened: false,
      awakeningAbility: null,
      recent: false
    }
  ],

  // ─────────────────────────────────────────────
  // PARAMECIA
  // ─────────────────────────────────────────────
  paramecia: [
    {
      id: "bara-bara",
      name: "Bara Bara no Mi",
      englishName: "Chop-Chop Fruit",
      ability: "Allows the user to split their body into separate parts that can be controlled remotely. The user is immune to being cut by bladed weapons.",
      chapter: 9,
      arc: "Orange Town Arc",
      previousOwners: [],
      currentOwner: "Buggy",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "sube-sube",
      name: "Sube Sube no Mi",
      englishName: "Smooth-Smooth Fruit",
      ability: "Makes the user's body perfectly smooth, causing attacks and physical contact to slide off without effect.",
      chapter: 98,
      arc: "Loguetown Arc",
      previousOwners: [],
      currentOwner: "Alvida",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "bomu-bomu",
      name: "Bomu Bomu no Mi",
      englishName: "Bomb-Bomb Fruit",
      ability: "Allows the user to make any part of their body explosive — including breath, sweat, and hair.",
      chapter: 110,
      arc: "Whiskey Peak Arc",
      previousOwners: [],
      currentOwner: "Mr. 5 (Gem)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "kilo-kilo",
      name: "Kilo Kilo no Mi",
      englishName: "Kilo-Kilo Fruit",
      ability: "Allows the user to change their body weight between 1 and 10,000 kilograms at will.",
      chapter: 108,
      arc: "Whiskey Peak Arc",
      previousOwners: [],
      currentOwner: "Miss Valentine",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "hana-hana",
      name: "Hana Hana no Mi",
      englishName: "Flower-Flower Fruit",
      ability: "Allows the user to sprout copies of body parts — hands, eyes, ears — from any surface. Damage to sprouted limbs is reflected onto the user.",
      chapter: 130,
      arc: "Reverse Mountain / Whiskey Peak Arc",
      previousOwners: [],
      currentOwner: "Nico Robin",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "doru-doru",
      name: "Doru Doru no Mi",
      englishName: "Wax-Wax Fruit",
      ability: "Allows the user to produce candle wax from their body and harden it into extremely durable structures.",
      chapter: 128,
      arc: "Alabasta Arc",
      previousOwners: [],
      currentOwner: "Mr. 3 (Galdino)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "baku-baku",
      name: "Baku Baku no Mi",
      englishName: "Munch-Munch Fruit",
      ability: "Allows the user to eat and digest anything, and then replicate or incorporate what they consume into their body — including weapons or entire ships.",
      chapter: 139,
      arc: "Drum Island Arc",
      previousOwners: [],
      currentOwner: "Wapol",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "mane-mane",
      name: "Mane Mane no Mi",
      englishName: "Clone-Clone Fruit",
      ability: "Allows the user to perfectly replicate the appearance of anyone they have touched — including voice and mannerisms.",
      chapter: 190,
      arc: "Alabasta Arc",
      previousOwners: ["Kurozumi Higurashi (deceased)"],
      currentOwner: "Bentham (Mr. 2 Bon Clay)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "supa-supa",
      name: "Supa Supa no Mi",
      englishName: "Dice-Dice Fruit",
      ability: "Turns every part of the user's body into razor-sharp steel blades — from hands to legs to the entire torso.",
      chapter: 190,
      arc: "Alabasta Arc",
      previousOwners: [],
      currentOwner: "Daz Bonez (Mr. 1)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "toge-toge",
      name: "Toge Toge no Mi",
      englishName: "Spike-Spike Fruit",
      ability: "Allows the user to grow and control razor-sharp spikes from any part of their body.",
      chapter: 190,
      arc: "Alabasta Arc",
      previousOwners: [],
      currentOwner: "Miss Doublefinger (Zala)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "ori-ori",
      name: "Ori Ori no Mi",
      englishName: "Bind-Bind Fruit",
      ability: "Allows the user to bind opponents with iron shackles that form on contact, restraining them completely.",
      chapter: 161,
      arc: "Alabasta Arc",
      previousOwners: [],
      currentOwner: "Hina",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "bane-bane",
      name: "Bane Bane no Mi",
      englishName: "Spring-Spring Fruit",
      ability: "Transforms the user's legs into powerful springs, enabling enormous leaping ability and spring-powered striking attacks.",
      chapter: 223,
      arc: "Jaya Arc",
      previousOwners: [],
      currentOwner: "Bellamy",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "noro-noro",
      name: "Noro Noro no Mi",
      englishName: "Slow-Slow Fruit",
      ability: "Emits Noroma Photons that slow down anything they strike to 1/30th of normal speed for exactly 30 seconds.",
      chapter: 307,
      arc: "Long Ring Long Land Arc",
      previousOwners: [],
      currentOwner: "Foxy",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "doa-doa",
      name: "Doa Doa no Mi",
      englishName: "Door-Door Fruit",
      ability: "Allows the user to create doors in any surface — walls, floors, air — and pass through them freely.",
      chapter: 402,
      arc: "Water 7 Arc",
      previousOwners: [],
      currentOwner: "Blueno",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "awa-awa",
      name: "Awa Awa no Mi",
      englishName: "Bubble-Bubble Fruit",
      ability: "Allows the user to produce soap bubbles that strip away the strength of anyone they cover — effectively washing away power and Haki.",
      chapter: 425,
      arc: "Enies Lobby Arc",
      previousOwners: [],
      currentOwner: "Kalifa",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "beri-beri",
      name: "Beri Beri no Mi",
      englishName: "Berry-Berry Fruit",
      ability: "Allows the user to split their body into hundreds of berry-like spheres that can move and attack independently.",
      chapter: 395,
      arc: "Post-Enies Lobby Arc",
      previousOwners: [],
      currentOwner: "Very Good",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "sabi-sabi",
      name: "Sabi Sabi no Mi",
      englishName: "Rust-Rust Fruit",
      ability: "Allows the user to rust and corrode metal on contact, instantly destroying weapons and armor.",
      chapter: 393,
      arc: "Enies Lobby Arc",
      previousOwners: [],
      currentOwner: "Shu",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "shari-shari",
      name: "Shari Shari no Mi",
      englishName: "Wheel-Wheel Fruit",
      ability: "Transforms the user's limbs into spinning wheels, enabling high-speed rotation attacks.",
      chapter: 395,
      arc: "Post-Enies Lobby Arc",
      previousOwners: [],
      currentOwner: "Sharinguru",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "yomi-yomi",
      name: "Yomi Yomi no Mi",
      englishName: "Revive-Revive Fruit",
      ability: "Grants one extra life after death. The user's soul can return to the living world and re-inhabit their body. The soul can also separate from the body to interact with and chill the environment.",
      chapter: 442,
      arc: "Thriller Bark Arc",
      previousOwners: [],
      currentOwner: "Brook",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "kage-kage",
      name: "Kage Kage no Mi",
      englishName: "Shadow-Shadow Fruit",
      ability: "Allows the user to manifest and control shadows. They can steal others' shadows and insert them into corpses, creating powerful undead zombie soldiers.",
      chapter: 444,
      arc: "Thriller Bark Arc",
      previousOwners: [],
      currentOwner: "Gecko Moria",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "horo-horo",
      name: "Horo Horo no Mi",
      englishName: "Hollow-Hollow Fruit",
      ability: "Allows the user to create ghosts from their body. Negative Hollow ghosts induce extreme depression in anyone they pass through. The user can also project their soul externally.",
      chapter: 444,
      arc: "Thriller Bark Arc",
      previousOwners: [],
      currentOwner: "Perona",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "suke-suke",
      name: "Suke Suke no Mi",
      englishName: "Clear-Clear Fruit",
      ability: "Allows the user to turn themselves and anything they are holding completely invisible.",
      chapter: 444,
      arc: "Thriller Bark Arc",
      previousOwners: ["Absalom (deceased)"],
      currentOwner: "Shiryu",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "nikyu-nikyu",
      name: "Nikyu Nikyu no Mi",
      englishName: "Paw-Paw Fruit",
      ability: "Gives the user paw pads that repel anything they touch at the speed of light — including pain, memories, and air itself, which can be compressed into devastating pressure paws.",
      chapter: 484,
      arc: "Thriller Bark Arc",
      previousOwners: [],
      currentOwner: "Bartholomew Kuma",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "ope-ope",
      name: "Ope Ope no Mi",
      englishName: "Op-Op Fruit",
      ability: "Creates a spherical 'ROOM' in which the user has total spatial control — rearranging objects, people, and organs freely. Can also perform the Perennial Youth Operation to grant another person immortality at the cost of the user's life.",
      chapter: 699,
      arc: "Dressrosa Arc (backstory Ch. 764)",
      previousOwners: ["Diez Barrels"],
      currentOwner: "Trafalgar D. Water Law",
      awakened: true,
      awakeningAbility: "The ROOM expands dramatically and the user can apply surgical techniques on an environmental scale — restructuring entire areas of terrain.",
      recent: false
    },
    {
      id: "shiro-shiro",
      name: "Shiro Shiro no Mi",
      englishName: "Castle-Castle Fruit",
      ability: "Allows the user to become a living fortress — their body contains an entire castle interior complete with a crew, cannons, and a miniature army.",
      chapter: 812,
      arc: "Zou Arc",
      previousOwners: [],
      currentOwner: "Capone Bege",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "wara-wara",
      name: "Wara Wara no Mi",
      englishName: "Straw-Straw Fruit",
      ability: "Allows the user to redirect damage to straw dolls representing others — effectively transferring injuries from the user to targeted individuals.",
      chapter: 498,
      arc: "Sabaody Archipelago Arc",
      previousOwners: [],
      currentOwner: "Basil Hawkins",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "ito-ito",
      name: "Ito Ito no Mi",
      englishName: "String-String Fruit",
      ability: "Allows the user to create and manipulate razor-sharp strings capable of slicing through ships and controlling people like marionettes.",
      chapter: 700,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Donquixote Doflamingo",
      awakened: true,
      awakeningAbility: "Covers an entire island in an inescapable 'Birdcage' of strings that slowly close in — converting the environment into a cutting death trap.",
      recent: false
    },
    {
      id: "zushi-zushi",
      name: "Zushi Zushi no Mi",
      englishName: "Press-Press Fruit",
      ability: "Grants the ability to manipulate gravitational forces — pulling meteorites from space and pressing opponents into the ground with immense gravity.",
      chapter: 701,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Fujitora (Issho)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "bari-bari",
      name: "Bari Bari no Mi",
      englishName: "Barrier-Barrier Fruit",
      ability: "Grants the ability to generate impenetrable barriers. The barriers cannot be broken by any conventional force — only Luffy has ever smashed through one.",
      chapter: 706,
      arc: "Dressrosa Arc",
      previousOwners: ["Kurozumi Semimaru (deceased)"],
      currentOwner: "Bartolomeo",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "nui-nui",
      name: "Nui Nui no Mi",
      englishName: "Stitch-Stitch Fruit",
      ability: "Allows the user to stitch people and objects to surfaces or to each other using giant needle-like arms.",
      chapter: 719,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Leo",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "giro-giro",
      name: "Giro Giro no Mi",
      englishName: "Glare-Glare Fruit",
      ability: "Grants x-ray vision capable of seeing through anything, reading minds, and projecting memories as shared illusions.",
      chapter: 700,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Viola",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "ato-ato",
      name: "Ato Ato no Mi",
      englishName: "Art-Art Fruit",
      ability: "Allows the user to transform anything — people, objects, space — into abstract art, stripping their physical form.",
      chapter: 699,
      arc: "Punk Hazard Arc",
      previousOwners: [],
      currentOwner: "Jora",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "jake-jake",
      name: "Jake Jake no Mi",
      englishName: "Jacket-Jacket Fruit",
      ability: "Allows the user to transform into a jacket worn by another person, controlling their movements from outside their body.",
      chapter: 705,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Kelly Funk",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "pamu-pamu",
      name: "Pamu Pamu no Mi",
      englishName: "Pop-Pop Fruit",
      ability: "Allows the user to cause any inorganic object — or parts of their own body — to rupture and explode.",
      chapter: 713,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Gladius",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "hobi-hobi",
      name: "Hobi Hobi no Mi",
      englishName: "Hobby-Hobby Fruit",
      ability: "Allows the user to transform humans into toys on contact. Anyone who knew the person instantly forgets they existed. As a side effect, the user does not age.",
      chapter: 706,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Sugar",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "sui-sui",
      name: "Sui Sui no Mi",
      englishName: "Swim-Swim Fruit",
      ability: "Allows the user to swim through solid surfaces — floors, walls, and ground — as if they were water.",
      chapter: 709,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Senor Pink",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "ton-ton",
      name: "Ton Ton no Mi",
      englishName: "Ton-Ton Fruit",
      ability: "Allows the user to multiply their body weight to tens of thousands of tons, turning themselves into a devastating falling projectile.",
      chapter: 704,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Machvise",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "ishi-ishi",
      name: "Ishi Ishi no Mi",
      englishName: "Stone-Stone Fruit",
      ability: "Allows the user to merge with and control stone — assimilating into rock structures and reshaping them at will.",
      chapter: 700,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Pica",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "beta-beta",
      name: "Beta Beta no Mi",
      englishName: "Mucus-Mucus Fruit",
      ability: "Allows the user to produce an extremely adhesive mucus that can immobilize opponents and coat surroundings.",
      chapter: 682,
      arc: "Punk Hazard Arc",
      previousOwners: [],
      currentOwner: "Trebol",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "buku-buku",
      name: "Buku Buku no Mi",
      englishName: "Book-Book Fruit",
      ability: "Allows the user to store people or objects inside books and create a 'Book World' — a pocket dimension within the pages.",
      chapter: 845,
      arc: "Whole Cake Island Arc",
      previousOwners: [],
      currentOwner: "Charlotte Mont-d'Or",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "pero-pero",
      name: "Pero Pero no Mi",
      englishName: "Lick-Lick Fruit",
      ability: "Allows the user to generate and control candy from their body — crafting hard armor, weapons, and structures.",
      chapter: 860,
      arc: "Whole Cake Island Arc",
      previousOwners: [],
      currentOwner: "Charlotte Perospero",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "bisu-bisu",
      name: "Bisu Bisu no Mi",
      englishName: "Biscuit-Biscuit Fruit",
      ability: "Allows the user to produce and infinitely harden biscuits from their body — crafting enormous armored soldiers.",
      chapter: 835,
      arc: "Whole Cake Island Arc",
      previousOwners: [],
      currentOwner: "Charlotte Cracker",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "memo-memo",
      name: "Memo Memo no Mi",
      englishName: "Memo-Memo Fruit",
      ability: "Allows the user to extract, view, and edit memories from a person's mind like strips of film.",
      chapter: 827,
      arc: "Whole Cake Island Arc",
      previousOwners: [],
      currentOwner: "Charlotte Pudding",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "mira-mira",
      name: "Mira Mira no Mi",
      englishName: "Mirror-Mirror Fruit",
      ability: "Allows the user to create and control mirrors that reflect attacks and serve as portals. The user can access the Mirror World — a parallel dimension inside reflective surfaces.",
      chapter: 843,
      arc: "Whole Cake Island Arc",
      previousOwners: [],
      currentOwner: "Charlotte Brulee",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "kuri-kuri",
      name: "Kuri Kuri no Mi",
      englishName: "Cream-Cream Fruit",
      ability: "Allows the user to produce scalding cream from their body, used offensively to scorch opponents.",
      chapter: 845,
      arc: "Whole Cake Island Arc",
      previousOwners: [],
      currentOwner: "Charlotte Opera",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "bata-bata",
      name: "Bata Bata no Mi",
      englishName: "Butter-Butter Fruit",
      ability: "Allows the user to produce and control butter — coating the ground and opponents to make surfaces frictionless.",
      chapter: 880,
      arc: "Whole Cake Island Arc",
      previousOwners: [],
      currentOwner: "Charlotte Galette",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "mochi-mochi",
      name: "Mochi Mochi no Mi",
      englishName: "Mochi-Mochi Fruit",
      ability: "Allows the user to create and control mochi — a sticky, elastic substance. Functions in a Logia-like manner in its awakened state, making it a Special Paramecia.",
      chapter: 882,
      arc: "Whole Cake Island Arc",
      previousOwners: [],
      currentOwner: "Charlotte Katakuri",
      awakened: true,
      awakeningAbility: "The user converts the environment into mochi — immobilizing opponents in sticky terrain while dramatically enhancing attack power.",
      recent: false
    },
    {
      id: "soru-soru",
      name: "Soru Soru no Mi",
      englishName: "Soul-Soul Fruit",
      ability: "Allows the user to extract and manipulate souls, converting life energy into 'Homies' — inanimate objects given life. Cannot affect those without fear of death.",
      chapter: 866,
      arc: "Whole Cake Island Arc",
      previousOwners: ["Mother Carmel (deceased — fruit passed upon her death)"],
      currentOwner: "Charlotte Linlin (Big Mom)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "kuku-kuku",
      name: "Kuku Kuku no Mi",
      englishName: "Cook-Cook Fruit",
      ability: "Allows the user to cook and transform any material into food — including converting ships and buildings into edible ingredients.",
      chapter: 871,
      arc: "Whole Cake Island Arc",
      previousOwners: [],
      currentOwner: "Streusen",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "gocha-gocha",
      name: "Gocha Gocha no Mi",
      englishName: "Combine-Combine Fruit",
      ability: "Allows multiple people to fuse their bodies together into one composite person with combined strength.",
      chapter: 871,
      arc: "Whole Cake Island Arc",
      previousOwners: [],
      currentOwner: "Charlotte Newshi",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "kobu-kobu",
      name: "Kobu Kobu no Mi",
      englishName: "Pump-Pump Fruit",
      ability: "Allows the user to inspire and dramatically boost the fighting spirit and physical capabilities of allies around them.",
      chapter: 904,
      arc: "Levely Arc",
      previousOwners: [],
      currentOwner: "Belo Betty",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "oshi-oshi",
      name: "Oshi Oshi no Mi",
      englishName: "Push-Push Fruit",
      ability: "Allows the user to push and reshape the ground as if it were clay — creating tunnel systems, walls, and terrain features.",
      chapter: 904,
      arc: "Levely Arc",
      previousOwners: [],
      currentOwner: "Morley",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "toki-toki",
      name: "Toki Toki no Mi",
      englishName: "Time-Time Fruit",
      ability: "Allows the user to send themselves or others forward in time. Cannot travel to the past — only into the future.",
      chapter: 960,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Kozuki Toki (deceased — fruit reincarnated)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "juku-juku",
      name: "Juku Juku no Mi",
      englishName: "Ripe-Ripe Fruit",
      ability: "Allows the user to rapidly age and decay anything they touch — rotting food, rusting weapons, or crumbling structures instantly.",
      chapter: 924,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Shinobu",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "fuku-fuku",
      name: "Fuku Fuku no Mi",
      englishName: "Garb-Garb Fruit",
      ability: "Allows the user to generate and change the clothing and appearance of themselves or others using leaves as a medium.",
      chapter: 919,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Kin'emon",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "maki-maki",
      name: "Maki Maki no Mi",
      englishName: "Scroll-Scroll Fruit",
      ability: "Allows the user to store objects and techniques inside scrolls and release them on command — similar to ninjutsu scroll sealing.",
      chapter: 912,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Raizo",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "jiki-jiki",
      name: "Jiki Jiki no Mi",
      englishName: "Magnet-Magnet Fruit",
      ability: "Allows the user to generate powerful electromagnetic fields — attracting and repelling metal objects over a vast range.",
      chapter: 929,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Eustass Kid",
      awakened: true,
      awakeningAbility: "The user can magnetize entire islands and opponents, accumulating enormous metal constructs from the surrounding environment.",
      recent: false
    },
    {
      id: "riki-riki",
      name: "Riki Riki no Mi",
      englishName: "Strong-Strong Fruit",
      ability: "Grants the user an extraordinary multiplying of physical strength — exponentially amplifying the force behind their strikes and grip.",
      chapter: 1099,
      arc: "Egghead Arc",
      previousOwners: [],
      currentOwner: "Jesus Burgess",
      awakened: false,
      awakeningAbility: null,
      recent: true
    },
    {
      id: "shiku-shiku",
      name: "Shiku Shiku no Mi",
      englishName: "Sick-Sick Fruit",
      ability: "Allows the user to infect others with various diseases by touch, spreading illness as a weapon.",
      chapter: 1099,
      arc: "Egghead Arc",
      previousOwners: [],
      currentOwner: "Doc Q",
      awakened: false,
      awakeningAbility: null,
      recent: true
    },
    {
      id: "wapu-wapu",
      name: "Wapu Wapu no Mi",
      englishName: "Warp-Warp Fruit",
      ability: "Allows the user to teleport themselves or others across vast distances instantly.",
      chapter: 1099,
      arc: "Egghead Arc",
      previousOwners: [],
      currentOwner: "Van Augur",
      awakened: false,
      awakeningAbility: null,
      recent: true
    },
    {
      id: "gunyo-gunyo",
      name: "Gunyo Gunyo no Mi",
      englishName: "Clay-Clay Fruit",
      ability: "Allows the user to generate and manipulate clay, shaping it into soldiers and structures.",
      chapter: 1080,
      arc: "Egghead Arc",
      previousOwners: [],
      currentOwner: "Prince Grus",
      awakened: false,
      awakeningAbility: null,
      recent: true
    },
    {
      id: "nomi-nomi",
      name: "Nomi Nomi no Mi",
      englishName: "Brain-Brain Fruit",
      ability: "Grants the user an infinitely expandable memory and intellect — retaining everything ever read, observed, or heard with perfect recall.",
      chapter: 1065,
      arc: "Egghead Arc",
      previousOwners: [],
      currentOwner: "Dr. Vegapunk (Stella)",
      awakened: false,
      awakeningAbility: null,
      recent: true
    },
    {
      id: "shima-shima",
      name: "Shima Shima no Mi",
      englishName: "Isle-Isle Fruit",
      ability: "Allows the user to merge with and become an island — controlling the terrain, emerging from the ground, and attacking with landmasses.",
      chapter: 1080,
      arc: "Egghead Arc",
      previousOwners: [],
      currentOwner: "Avalo Pizarro",
      awakened: false,
      awakeningAbility: null,
      recent: true
    },
    {
      id: "poke-poke",
      name: "Poke Poke no Mi",
      englishName: "Pocket-Pocket Fruit",
      ability: "Creates pockets within the user's body capable of storing an unlimited number of items of any size.",
      chapter: 234,
      arc: "Jaya Arc (ability confirmed later)",
      previousOwners: [],
      currentOwner: "Blamenco",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "chiyu-chiyu",
      name: "Chiyu Chiyu no Mi",
      englishName: "Heal-Heal Fruit",
      ability: "Grants the ability to heal injuries — the user's tears have powerful restorative properties that can rapidly close wounds.",
      chapter: 742,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Mansherry",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "fude-fude",
      name: "Fude Fude no Mi",
      englishName: "Brush-Brush Fruit",
      ability: "Allows the user to bring drawings to life — anything painted or drawn becomes a real, functioning entity.",
      chapter: 964,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Kurozumi Kanjuro",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "kibi-kibi",
      name: "Kibi Kibi no Mi",
      englishName: "Millet-Millet Fruit",
      ability: "Allows the user to produce kibi dango (millet dumplings) that, when eaten by animals, tame them and make them fully obedient.",
      chapter: 918,
      arc: "Wano Country Arc",
      previousOwners: [],
      currentOwner: "Tama",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "gura-gura",
      name: "Gura Gura no Mi",
      englishName: "Tremor-Tremor Fruit",
      ability: "Allows the user to create massive vibrations and shockwaves capable of destroying ships, shattering the air itself, and triggering tsunamis. Said to hold the power to destroy the world.",
      chapter: 552,
      arc: "Marineford Arc",
      previousOwners: ["Edward Newgate (Whitebeard, deceased)"],
      currentOwner: "Marshall D. Teach (Blackbeard)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "doku-doku",
      name: "Doku Doku no Mi",
      englishName: "Venom-Venom Fruit",
      ability: "Allows the user to produce and control various types of poison from their body — ranging from paralysis-inducing to near-instantly lethal.",
      chapter: 526,
      arc: "Impel Down Arc",
      previousOwners: [],
      currentOwner: "Magellan",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "horu-horu",
      name: "Horu Horu no Mi",
      englishName: "Horm-Horm Fruit",
      ability: "Allows the user to produce and inject special hormones into others — granting boosts to strength, speed, healing, or even changing a person's sex.",
      chapter: 537,
      arc: "Impel Down Arc",
      previousOwners: [],
      currentOwner: "Emporio Ivankov",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "choki-choki",
      name: "Choki Choki no Mi",
      englishName: "Snip-Snip Fruit",
      ability: "Transforms the user's hands into giant scissors capable of cutting anything — including solid stone and even abstract concepts of space.",
      chapter: 537,
      arc: "Impel Down Arc",
      previousOwners: [],
      currentOwner: "Inazuma",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "fuwa-fuwa",
      name: "Fuwa Fuwa no Mi",
      englishName: "Float-Float Fruit",
      ability: "Allows the user to levitate and freely control any non-living object they have touched, lifting anything from people to islands.",
      chapter: 0,
      arc: "Strong World (Film)",
      previousOwners: [],
      currentOwner: "Shiki",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "mato-mato",
      name: "Mato Mato no Mi",
      englishName: "Mark-Mark Fruit",
      ability: "Allows the user to mark a target so that anything the user throws will home in on that target with perfect accuracy.",
      chapter: 612,
      arc: "Fishman Island Arc",
      previousOwners: [],
      currentOwner: "Vander Decken IX",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "mero-mero",
      name: "Mero Mero no Mi",
      englishName: "Love-Love Fruit",
      ability: "Allows the user to turn anyone who feels attraction toward them to stone — permanently until the user reverses the effect.",
      chapter: 521,
      arc: "Amazon Lily Arc",
      previousOwners: [],
      currentOwner: "Boa Hancock",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "guru-guru",
      name: "Guru Guru no Mi",
      englishName: "Spin-Spin Fruit",
      ability: "Allows the user to rotate their body or limbs at extreme speeds, functioning as propellers for flight and powering devastating spin attacks.",
      chapter: 682,
      arc: "Punk Hazard Arc",
      previousOwners: [],
      currentOwner: "Buffalo",
      awakened: false,
      awakeningAbility: null,
      recent: false
    },
    {
      id: "nagi-nagi",
      name: "Nagi Nagi no Mi",
      englishName: "Calm-Calm Fruit",
      ability: "Allows the user to create a soundproof field, nullifying all sound within an area. The user can also silence themselves to move without making noise.",
      chapter: 763,
      arc: "Dressrosa Arc",
      previousOwners: [],
      currentOwner: "Donquixote Rosinante (Corazon, deceased)",
      awakened: false,
      awakeningAbility: null,
      recent: false
    }
  ]
};

// Fruits marked recent (newest reveals) for homepage
const recentFruits = [
  ...devilFruits.logia.filter(f => f.recent),
  ...devilFruits.zoan.filter(f => f.recent),
  ...devilFruits.paramecia.filter(f => f.recent)
];
